import {
  Home,
  Download,
  Zap,
  CircleHelp,
  Settings,
  Brain,
  Key,
  HelpCircle,
  Book,
  Bot,
  PersonStandingIcon,
  Image,
  MessageCircle,
  AudioLines,
  BookOpen,
  Compass,
  Users,
  MessageSquare,
  HardDrive,
  Heart,
  Plug,
  Shield,
  BarChart3,
  Archive,
  Mic,
  LayoutDashboard,
  GitBranch,
} from "lucide-react";
import { Wheelchair } from "./WheelChairIcon";

export const docsNav = [
  {
    title: "Getting Started",
    items: [
      {
        title: "Introduction",
        href: "/docs",
        icon: Home,
        keywords: ["home", "start", "welcome", "overview"],
      },
      {
        title: "Installation",
        href: "/docs/installation",
        icon: Download,
        keywords: ["install", "download", "setup", "android", "apk"],
      },
      {
        title: "Quick Start",
        href: "/docs/quickstart",
        icon: Zap,
        keywords: ["quick", "start", "begin", "first", "tutorial"],
      },
      {
        title: "AI Basics",
        href: "/docs/ai-basics",
        icon: CircleHelp,
        keywords: [
          "ai basics",
          "beginner",
          "token",
          "tokens",
          "context",
          "context window",
          "how ai works",
        ],
      },
    ],
  },
  {
    title: "Configuration",
    items: [
      {
        title: "API Keys",
        href: "/docs/api-keys",
        icon: Key,
        keywords: [
          "api",
          "key",
          "openai",
          "anthropic",
          "claude",
          "gemini",
          "token",
        ],
      },
      {
        title: "Providers",
        href: "/docs/providers",
        icon: Settings,
        keywords: [
          "provider",
          "model",
          "ollama",
          "local",
          "endpoint",
          "custom",
        ],
      },
      {
        title: "Models",
        href: "/docs/models",
        icon: Bot,
        keywords: [
          "model",
          "provider",
          "ollama",
          "local",
          "endpoint",
          "custom",
        ],
      },
      {
        title: "Model Browser & Local Inference",
        href: "/docs/model-browser",
        icon: HardDrive,
        keywords: [
          "model browser",
          "llama.cpp",
          "llamacpp",
          "ollama",
          "local",
          "gguf",
          "download",
          "huggingface",
          "inference",
          "gpu",
          "offline",
        ],
      },
      {
        title: "Ollama",
        href: "/docs/ollama",
        icon: Settings,
        keywords: [
          "ollama",
          "local",
          "server",
          "self-hosted",
          "inference",
          "mirostat",
        ],
      },
      {
        title: "Host API",
        href: "/docs/host-api",
        icon: Plug,
        keywords: [
          "host api",
          "openai compatible",
          "local server",
          "http",
          "sse",
          "integration",
          "rest",
        ],
      },
      {
        title: "Image Generation",
        href: "/docs/images",
        icon: Image,
        keywords: ["image", "generation", "in-chat", "images", "img"],
      },
      {
        title: "Accessibility",
        href: "/docs/accessibility",
        icon: Wheelchair,
        keywords: [
          "accessibility",
          "a11y",
          "screen reader",
          "contrast",
          "usability",
        ],
      },
    ],
  },
  {
    title: "Features",
    items: [
      {
        title: "Characters",
        href: "/docs/characters",
        icon: Bot,
        keywords: [
          "character",
          "persona",
          "personality",
          "avatar",
          "system prompt",
        ],
      },
      {
        title: "Chat Templates",
        href: "/docs/chat-templates",
        icon: MessageSquare,
        keywords: [
          "chat template",
          "starter",
          "opening messages",
          "conversation starter",
          "scene",
        ],
      },
      {
        title: "Personas",
        href: "/docs/personas",
        icon: PersonStandingIcon,
        keywords: ["persona", "personality", "role", "voice", "user"],
      },
      {
        title: "Group Chats",
        href: "/docs/group-chats",
        icon: Users,
        keywords: ["group chat", "multi character", "conversation", "roleplay"],
      },
      {
        title: "Chat Widgets",
        href: "/docs/chat-widgets",
        icon: LayoutDashboard,
        keywords: [
          "widget",
          "widgets",
          "panel",
          "side panel",
          "stat tracker",
          "scratch pad",
          "dice",
          "layout",
        ],
      },
      {
        title: "Chat Branching",
        href: "/docs/branching",
        icon: GitBranch,
        keywords: [
          "branch",
          "branching",
          "fork",
          "tree",
          "lineage",
          "alternate",
          "timeline",
          "compare",
        ],
      },
      {
        title: "Discovery",
        href: "/docs/discovery",
        icon: Compass,
        keywords: [
          "discovery",
          "character tavern",
          "browse",
          "search",
          "import",
        ],
      },
      {
        title: "System Prompts",
        href: "/docs/system-prompts",
        icon: Settings,
        keywords: ["system", "prompt", "instructions", "behavior", "rules"],
      },
      {
        title: "Companion Mode",
        href: "/docs/companion-mode",
        icon: Heart,
        keywords: [
          "companion",
          "relationship",
          "soul",
          "emotion",
          "bond",
          "roleplay",
        ],
      },
      {
        title: "Memory System",
        href: "/docs/memory",
        icon: Brain,
        keywords: [
          "memory",
          "context",
          "history",
          "remember",
          "infinite",
          "summarization",
        ],
      },
      {
        title: "Lorebooks",
        href: "/docs/lorebooks",
        icon: Book,
        keywords: ["lorebook", "lore", "lorebook", "lorebook", "lorebook"],
      },
      {
        title: "Sync",
        href: "/docs/sync",
        icon: Zap,
        keywords: ["sync", "cloud", "backup", "restore", "accounts"],
      },
      {
        title: "Help Me Reply",
        href: "/docs/help-me-reply",
        icon: MessageCircle,
        keywords: ["autofill", "autocomplete", "replyasuser"],
      },
      {
        title: "Text to Speech",
        href: "/docs/tts",
        icon: AudioLines,
        keywords: ["text to speech", "tts", "voice", "speak", "audio"],
      },
      {
        title: "Speech Recognition",
        href: "/docs/speech-recognition",
        icon: Mic,
        keywords: [
          "speech",
          "recognition",
          "asr",
          "whisper",
          "voice input",
          "dictation",
          "microphone",
        ],
      },
      {
        title: "Smart Creator",
        href: "/docs/smart-creator",
        icon: BookOpen,
        keywords: [
          "smart creator",
          "character creator",
          "create character",
          "persona",
          "lorebook",
        ],
      },
    ],
  },
  {
    title: "Privacy & Data",
    items: [
      {
        title: "Security",
        href: "/docs/security",
        icon: Shield,
        keywords: [
          "security",
          "pure mode",
          "content filter",
          "trusted certificates",
          "analytics",
          "privacy",
        ],
      },
      {
        title: "Usage",
        href: "/docs/usage",
        icon: BarChart3,
        keywords: [
          "usage",
          "tokens",
          "cost",
          "activity",
          "tracking",
          "csv",
          "stats",
        ],
      },
      {
        title: "Backup & Restore",
        href: "/docs/backup-restore",
        icon: Archive,
        keywords: [
          "backup",
          "restore",
          "export",
          "import",
          "encrypted",
          "reset",
        ],
      },
    ],
  },
  {
    title: "Help",
    items: [
      {
        title: "FAQ",
        href: "/faq",
        icon: HelpCircle,
        keywords: ["faq", "question", "help", "support", "common"],
      },
    ],
  },
];

export const allDocsItems = docsNav.flatMap((section) =>
  section.items.map((item) => ({ ...item, section: section.title })),
);
